### ISSUE TITLE
Won't work in docker..

### ISSUE THREAD

**Issue by philippkayser** [monitoror/monitoror#362]
We don't get it to work with this config. config.json is checked locally and works there but in docker we get **"Missing configPath or configUrl query param"**

```
version: '3'

services:
  monitoror:
    image: monitoror/monitoror
    environment:
      - "MO_PORT=8085"
      - "MO_CONFIG=/bin/config.json"
      - "MO_MONITORABLE_PING_COUNT=2"
      - "MO_MONITORABLE_PING_INTERVAL=100"
      - "MO_MONITORABLE_PING_TIMEOUT=1000"
      - "MO_ADDRESS=0.0.0.0"
    volumes:
      - ./config.json:/bin/config.json
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:url.domain...."
      - "traefik.port=8085"


networks:
  web:
     external: true
```

```
monitoror_1  |
monitoror_1  |     __  ___            _ __
monitoror_1  |    /  |/  /___  ____  (_) /_____  _________  _____
monitoror_1  |   / /|_/ / __ \/ __ \/ / __/ __ \/ ___/ __ \/ ___/
monitoror_1  |  / /  / / /_/ / / / / / /_/ /_/ / /  / /_/ / /
monitoror_1  | /_/  /_/\____/_/ /_/_/\__/\____/_/   \____/_/  4.0.0
monitoror_1  |
monitoror_1  | https://monitoror.com
monitoror_1  |
monitoror_1  |
monitoror_1  | ENABLED MONITORABLES
monitoror_1  |
monitoror_1  |   ✓ HTTP
monitoror_1  |   ✓ Ping
monitoror_1  |   ✓ Port
monitoror_1  |   ✓ Travis CI
monitoror_1  |
monitoror_1  | 5 more monitorables were ignored
monitoror_1  | Check the documentation to know how to enabled them:
monitoror_1  | https://monitoror.com/documentation/
monitoror_1  |
monitoror_1  |
monitoror_1  | AVAILABLE NAMED CONFIGURATIONS
monitoror_1  |
monitoror_1  |   default -> /bin/config.json
monitoror_1  |
monitoror_1  |
monitoror_1  | ─────────────────────────────────────────────────
monitoror_1  |
monitoror_1  | MONITOROR IS RUNNING AT:
monitoror_1  |   http://localhost:8085
monitoror_1  |   http://172.19.0.15:8085
monitoror_1  |
monitoror_1  | ─────────────────────────────────────────────────
monitoror_1  |
```
