### ISSUE TITLE
Docker image w. Config non-functional?

### ISSUE THREAD

**Issue by ghost** [monitoror/monitoror#412]
Hello!

First of all I think this seems like a great little tool and my apologies for, maybe, being too dumb to do things right.

I am trying to get a working example running using the Docker file and my own config file, and it won't run:

![billede](https://user-images.githubusercontent.com/110449962/215758185-631c8fd8-f56f-43f6-9e27-7379a73a46fd.png)

I tried to simplify the setup by packaging things in a `docker-compose` like so:

```yaml
version: '3.6'

services:
  monitoror:
    image: monitoror/monitoror
    environment:
      - "MO_PORT=8080"
      - "MO_CONFIG=/bin/config.json"
      - "MO_MONITORABLE_PING_COUNT=2"
      - "MO_MONITORABLE_PING_INTERVAL=100"
      - "MO_MONITORABLE_PING_TIMEOUT=1000"
      - "MO_ADDRESS=0.0.0.0"
    volumes:
      - ./config.json:/bin/config.json
```

The config-file itself is just a copy-paste of your example config:

```json
{
  "version": "2.0",
  "columns": 2,
  "tiles": [
    {
      "type": "PORT",
      "label": "Welcome config example",
      "params": {
        "hostname": "127.0.0.1",
        "port": 8080
      }
    },
    {
      "type": "HTTP-RAW",
      "label": "Monitoror stars",
      "params": {
        "url": "https://github.com/monitoror/monitoror",
        "regex": "(\\d+) users starred"
      }
    }
  ]
}
```

So what have I done wrong? Help! :(
