### ISSUE TITLE
not working under subpath prefix in kubernetes

### ISSUE THREAD

**Issue by bisegni** [monitoror/monitoror#421]
Hello i have problem working with kubernetes ingress:

i also have problem, i deployed it in kubernetes with:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoror-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: "myhostname.org"
    http:
      paths:
      - pathType: Prefix
        path: /status(/|$)(.*)
        backend:
          service:
            name: monitoror-service
            port: 
              number: 80
```

but the resurse are still searched starting from `myhostname.org `and not from `myhostname.org/status`

i verified that use the portforward with service `monitoror-service` it works perfectly

any idea?
