### ISSUE TITLE
Docker-compose javascript not enabled issues

### ISSUE THREAD

**Issue by wiktorkisielewski** [monitoror/monitoror#423]
I am trying to start a monitoror instance from docker-compose

```yaml
version: '3'

services:
  monitoror:
    image: monitoror/monitoror:4
    ports:
      - "8080:8080"
    environment:
      - "MO_PORT=8080"
      - "MO_MONITORABLE_PING_COUNT=2"
      - "MO_MONITORABLE_PING_INTERVAL=100"
      - "MO_MONITORABLE_PING_TIMEOUT=1000"
      - "MO_ADDRESS=0.0.0.0"
      - "MO_CONFIG=/bin/production.json"
    volumes:
      - ./production.json:/bin/production.json
```
 production.json is:
 ```json
 {
  "version": "2.0",
  "columns": 4,
  "zoom": 0.5,
  "tiles": [
    {
      "type": "HTTP-FORMATTED",
      "label": "Austria BE",
      "params": {
        "url": "https://my-domain.com/api/health/",
        "format": "JSON",
        "key": ".version"
      }
    },
    {
      "type": "HTTP-FORMATTED",
      "label": "Austria self-service",
      "params": {
        "url": "https://my-domain.com/version.json",
        "format": "JSON",
        "key": ".commit_hash"
      }
    }
  ]
}
 ```

it starts well, but then all I can see is:

> We're sorry but Monitoror doesn't work properly without JavaScript enabled. Please enable it to continue

[also when using `curl http://localhost:8080` from inside the container itself (added curl with `apk`]

There are no errors inside monitoror logs, what might be the issue here?
